# fly.toml app configuration file generated for thought-ink on 2025-10-09T05:00:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thought-ink'
primary_region = 'ewr'

[build]
  [build.args]
    GO_VERSION = '1.24.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
